"""add new tables and modify users , organizations tables

Revision ID: c5909ddd17aa
Revises: 4ed9083ef452
Create Date: 2026-09-08 21:20:36.880725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5909ddd17aa'
down_revision: Union[str, None] = '4ed9083ef452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('email_verification_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.add_column('organizations', sa.Column('legal_id', sa.String(length=50), nullable=False))
    op.add_column('organizations', sa.Column('country', sa.String(length=100), nullable=False))
    op.add_column('organizations', sa.Column('city', sa.String(length=100), nullable=False))
    op.add_column('organizations', sa.Column('phone', sa.String(length=30), nullable=False))
    op.add_column('organizations', sa.Column('address', sa.Text(), nullable=False))
    op.add_column('organizations', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('organizations', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('organizations', sa.Column('reviewed_by', sa.UUID(), nullable=True))
    op.add_column('organizations', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organizations', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'organizations', 'users', ['reviewed_by'], ['id'])
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('job_title', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('account_status', sa.String(length=20), nullable=False))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'account_status')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'job_title')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'rejection_reason')
    op.drop_column('organizations', 'reviewed_at')
    op.drop_column('organizations', 'reviewed_by')
    op.drop_column('organizations', 'status')
    op.drop_column('organizations', 'email')
    op.drop_column('organizations', 'website')
    op.drop_column('organizations', 'address')
    op.drop_column('organizations', 'phone')
    op.drop_column('organizations', 'city')
    op.drop_column('organizations', 'country')
    op.drop_column('organizations', 'legal_id')
    op.drop_table('organization_documents')
    op.drop_table('email_verification_codes')
    op.drop_table('account_invitations')
    # ### end Alembic commands ###
