"""replace cargo origin/destination with corridor_id, auto-generate reference

Revision ID: eccccabb9890
Revises: e7df4db88632
Create Date: 2026-09-10 21:54:20.016537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eccccabb9890'
down_revision: Union[str, None] = 'e7df4db88632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cargos', sa.Column('corridor_id', sa.UUID(), nullable=False))
    op.alter_column('cargos', 'reference',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_foreign_key(None, 'cargos', 'corridors', ['corridor_id'], ['id'])
    op.drop_column('cargos', 'origin')
    op.drop_column('cargos', 'destination')
    op.drop_index('ix_security_alerts_organization_id', table_name='security_alerts')
    op.drop_index('ix_security_alerts_status', table_name='security_alerts')
    op.drop_index('ix_security_alerts_tracker_id', table_name='security_alerts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_security_alerts_tracker_id', 'security_alerts', ['tracker_id'], unique=False)
    op.create_index('ix_security_alerts_status', 'security_alerts', ['status'], unique=False)
    op.create_index('ix_security_alerts_organization_id', 'security_alerts', ['organization_id'], unique=False)
    op.add_column('cargos', sa.Column('destination', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('cargos', sa.Column('origin', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cargos', type_='foreignkey')
    op.alter_column('cargos', 'reference',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('cargos', 'corridor_id')

    # ### end Alembic commands ###
