"""add msisdn and improve device metadata for CAMARA integration

Revision ID: f4408a2a08cb
Revises: eccccabb9890
Create Date: 2026-09-10 22:29:42.019421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4408a2a08cb'
down_revision: Union[str, None] = 'eccccabb9890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('trackers', sa.Column('label', sa.String(length=100), nullable=True))
    op.alter_column('trackers', 'device_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('trackers', 'msisdn',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trackers', 'msisdn',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('trackers', 'device_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('trackers', 'label')
    
    # ### end Alembic commands ###
